### PR TITLE
Feature/17  codrops nested accordion

### PR DESCRIPTION
**Pull request by jaredstevick**

### CODE REVIEW

**Comment by jaredstevick** [comment]
Link to current WIP:
https://github.com/TheIronYard--Orlando/FEE--2015--SPRING/issues/215

**Comment by jaredstevick** [comment]
## Crap that Doesn't Work:
- [ ] accordion doesn't open
- [ ] two sub articles are showing
- [ ] never got the down arrow in there
- [ ] margins could be better (not that you can tell since it doesn't open)

**Comment by sak55** [comment]
thumb thumb thumb :+1:

**Comment by johnalxndr** [comment]
:+1:

**Pull request merged**
