### PR TITLE
Pull Request for Feature/18--Hello-JQuery

### PR DESCRIPTION
**Pull request by jaredstevick**

### CODE REVIEW

**Comment by jaredstevick** [comment]
Link to current WIP:
https://github.com/TheIronYard--Orlando/FEE--2015--SPRING/issues/230

**Comment by johnalxndr** [comment]
:+1: bootstrap ftw

**Comment by sak55** [comment]
:+1:

**Comment by jaredstevick** [comment]
## Crap that sucks:
- [ ] Font and font weight.. blech
- [ ] Boxes need to be taller
- [ ] Center submit button
- [ ] Where does my data go?
- [ ] Really want to tackle the API and make responses end up in comments
- [ ] Allow multiple selections from dropdowns
- [x] Button color and text

**Pull request merged**
