### PR TITLE
Surf & Paddle Responsive Design

### PR DESCRIPTION
**Pull request by jaredstevick**

### CODE REVIEW

**Comment by jaredstevick** [comment]
**Link to current WIP:**
_Surf & Paddle Responsive Design:_
https://github.com/TheIronYard--Orlando/FEE--2015--SPRING/issues/108

**Comment by carolinapowers** [comment]
:+1:

**Comment by mfees** [comment]
:+1: 
woohoo

**Comment by jaredstevick** [comment]
Link to Surf & Paddle via htmlpreview: 

http://htmlpreview.github.io/?https://github.com/jaredstevick/TIY-Assignments/blob/feature/08--surf%2Bpaddle%2Brwd/index.html

**Comment by al-the-x** [comment]
Looks like all your files for S&P ended up in the project root rather than `pub/`... But I'm guessing you probably figured that out by now. How did that make you feel?

**Pull request merged**
