### PR TITLE
Feature/24  helluva ride -- katas

### PR DESCRIPTION
**Pull request by jaredstevick**

### CODE REVIEW

**Comment by johnalxndr** [comment]
:+1: yay

**Comment by mfees** [comment]
:+1: 

don't forget to put any known issues as a list somewhere

**Comment by jrutishauser** [comment]
:+1:

**Comment by jaredstevick** [comment]
Link to WIP:
https://github.com/TheIronYard--Orlando/FEE--2015--SPRING/issues/299

**Pull request merged**
